name: "Assign size label"
description: "Assign labels based on pull request change sizes"
inputs:
  sizes:
    description: "Custom size configuration"
    required: false
runs:
  using: "node16"
  main: "dist/index.js"
branding:
  icon: "tag"
  color: "blue"
